# Generated by Django 2.1.5 on 2019-03-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('clue_text', models.TextField()),
                ('points_to', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='clue_image')),
                ('solution', models.TextField()),
            ],
        ),
    ]
